config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations,:sessions]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  root 'store/main_page#index'

  get 'products/:id', to: 'store/products#show', as: 'product'
  get 'categories/:id', to: 'store/categories#show', as: 'category'
  get 'catalog', to: 'store/catalog#index'
  get 'brands', to: 'store/manufacturers#index', as: 'brands'
  get 'shops', to: 'store/shops#index', as: 'shops'
  get 'promos', to: 'store/promos#index', as: 'promos'
  get 'promos/:id', to: 'store/promos#show', as: 'promo'


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'products_light', to: 'products_light#index', as: 'products_light'
    resources :activity_logs, only: [:index]
    resources :categories
    resources :collections
    resources :products
    resources :pictures
    resources :sale_sizes
    resources :product_types
    resources :sizes
    resources :incrustations
    resources :incrustation_items
    resources :metal_colors
    resources :metal_types
    resources :kits
    resources :manufacturers
    resources :shops
    resources :chain_types
    resources :promos
    resources :slides
    resources :main_page_blocks
    resources :users
    resource :users, only: [:update_password, :edit_password] do
      collection do
        patch ':id/update_password', to: 'users#update_password'
        get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      end
    end
  end

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
  # изображение для списка производителей
  belongs_to :index, class_name: 'Picture', optional: true
  # изображение для слайдшоу брендов на главной
  belongs_to :slide, class_name: 'Picture', optional: true

  validates :title, presence: true, length: {in: 1..50}

  # значения для фильтра по вставкам
  def self.options_for_manufacturer_select
    order('LOWER(title)').map { |e| [e.title, e.id] }
  end
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < Admin::AdminController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  def index
    @manufacturers = Manufacturer.includes(:index).includes(:slide).all
  end


  def show
  end


  def new
    @manufacturer = Manufacturer.new
  end

  def edit
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if params[:index]
        index = Picture.create(image: params[:index])
        @manufacturer.index = index
    end
    if params[:slide]
      slide = Picture.create(image: params[:slide])
      @manufacturer.slide = slide
    end

    if @manufacturer.save
      record_activity(@manufacturer)
      redirect_to edit_admin_manufacturer_path(@manufacturer), notice: 'Производитель был успешно добавлен.'
    else
      render :new
    end
  end

  def update
    if params[:index]
      index = Picture.create(image: params[:index])
      @manufacturer.index = index
    end
    if params[:slide]
      slide = Picture.create(image: params[:slide])
      @manufacturer.slide = slide
    end
    if @manufacturer.update(manufacturer_params)
      record_activity(@manufacturer)
      redirect_to edit_admin_manufacturer_path(@manufacturer), notice: 'Производитель был успешно обновлен.'
    else
      render :edit
    end
  end

  def destroy
    if !@manufacturer.index.nil?
      @manufacturer.index.destroy
    end
    if !@manufacturer.slide.nil?
      @manufacturer.slide.destroy
    end
    @manufacturer.products.each do |product|
      product.manufacturer = nil
      product.save
    end
    @manufacturer_tmp = @manufacturer.dup
    @manufacturer.destroy
    record_activity(@manufacturer_tmp)
    redirect_to admin_manufacturers_url, notice: 'Производитель был успешно удален.'
  end

  private
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    def manufacturer_params
      params.require(:manufacturer).permit(:title, :description)
    end
end

app/controllers/store/manufacturers_controller.rb
class Store::ManufacturersController < Store::StoreController
  def index
    @brands = Manufacturer.includes(:index).all
  end
end

app/views/admin/manufacturers/_form.html.erb
<%= form_for([:admin,manufacturer], :html => {multipart: true}) do |f| %>
  <% if manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% manufacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :title, 'Название' %>
          <%= f.text_field :title, :placeholder => 'Введите название  ', class: 'form-control' %>
        </div>

        <div class="field-group">
          <%= f.label :description, 'Описание' %>
          <%= f.text_area :description,{class: 'form-control'} %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <!--Изображение в списке брендов-->
        <div class="form-group">
          <%= f.label :index, 'Изображение в списке брендов' %>

          <%= file_field_tag "index", class: 'form-control' %>
        </div>
        <% if manufacturer.index %>
            <%= link_to admin_picture_path(manufacturer.index), method: :delete,
                        :remote => true,
                        :class => 'delete-image',
                        data: { confirm: 'Фото будет удалено безвозвратно, Вы уверены?' } do %>
                <div class="btn btn-danger mb10">Удалить фото</div>
            <% end %>
            <%= image_tag manufacturer.index.image, class: 'img-responsive', style: 'max-height:300px; margin:auto'  %>
        <% end %>
      </div>
      <div class="col-lg-6">
        <!--Изображение слайдере брендов-->
        <div class="form-group">
          <%= f.label :slide, 'Изображение в слайдере' %>
          <%= file_field_tag "slide", class: 'form-control' %>
        </div>
        <% if manufacturer.slide %>
            <%= link_to admin_picture_path(manufacturer.slide), method: :delete,
                        :remote => true,
                        :class => 'delete-image',
                        data: { confirm: 'Фото будет удалено безвозвратно, Вы уверены?' } do %>
                <div class="btn btn-danger mb10">Удалить фото</div>
            <% end %>
            <div style="background: #c62828; padding: 10px">
              <%= image_tag manufacturer.slide.image, class: 'img-responsive', style: 'max-height:300px; border: 1px solid black; margin:auto' %>
            </div>
          <% end %>
      </div>
    </div>
    <div class="row mt10">
      <div class="actions text-center">
        <%= f.submit 'Применить', class: 'btn btn-success mb10 mr10' %>
      </div>
    </div>


<% end %>

app/views/admin/manufacturers/edit.html.erb
<div class="row">
  <h1 class="panel-heading">Редактирование производителя</h1>
  <div id="notice" class="alert alert-success"><%= notice %></div>
</div>
<div class="mb15">
  <%= link_to 'Показать', edit_admin_manufacturer_path(@manufacturer), class: 'btn btn-default mr10'  %>
  <%= link_to 'Назад', admin_manufacturers_path, class: 'btn btn-default'  %>
</div>
<%= render 'form', manufacturer: @manufacturer %>

app/views/admin/manufacturers/index.html.erb
<div class="row">
  <h1 class="panel-heading">Производители</h1>
  <div id="notice" class="alert alert-success"><%= notice %></div>
</div>
<%= link_to 'Все изделия', admin_products_path, class: 'btn btn-default' %>
<%= link_to new_admin_manufacturer_path, class: 'btn btn-success'  do %>
    Добавить производителя
    <i class="fa fa-plus"></i>
<% end %>
<br><br>
<div class="panel panel-default">
  <div class="panel-body">
    <table  width="100%" class="table table-striped table-bordered table-hover" id="simpleDataTable">
      <thead>
        <tr>
          <th>Название</th>
          <th>Описание</th>
          <th>Изделий</th>
          <th>Фото Банера</th>
          <th>Фото Слайда</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @manufacturers.each do |manufacturer| %>
          <tr>
            <td><%= manufacturer.title %></td>
            <td><%= truncate(manufacturer.description, length: 30)  %></td>
            <td><%= manufacturer.products.size %></td>
            <td>
              <% if manufacturer.index %>
                  <i class="fa fa-check" aria-hidden="true"></i>
              <% else %>
                  <i class="fa fa-times" aria-hidden="true"></i>
              <%end%>
            </td>
            <td>
              <% if manufacturer.slide %>
                  <i class="fa fa-check" aria-hidden="true"></i>
              <% else %>
                  <i class="fa fa-times" aria-hidden="true"></i>
              <%end%>
            </td>
            <td><%= link_to 'Показать', admin_manufacturer_path(manufacturer) %></td>
            <td><%= link_to 'Изменить', edit_admin_manufacturer_path(manufacturer) %></td>
            <td><%= link_to 'Удалить', admin_manufacturer_path(manufacturer), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/manufacturers/new.html.erb
<div class="row">
  <h1 class="panel-heading">Новый производитель</h1>
</div>

<%= link_to 'Назад', admin_manufacturers_path, class: 'btn btn-default mb10' %>

<%= render 'form', manufacturer: @manufacturer %>

app/views/admin/manufacturers/show.html.erb
<div class="row">
  <h1 class="panel-heading">Производитель</h1>
  <p id="notice"><%= notice %></p>
</div>
<p>
  <strong>Название:</strong>
  <%= @manufacturer.title %>
</p>

<%= link_to 'Изменить', edit_admin_manufacturer_path(@manufacturer),  class: 'btn btn-default mr10' %>
<%= link_to 'Назад', admin_manufacturers_path,  class: 'btn btn-default' %>