config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations,:sessions]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  root 'store/main_page#index'

  get 'products/:id', to: 'store/products#show', as: 'product'
  get 'categories/:id', to: 'store/categories#show', as: 'category'
  get 'catalog', to: 'store/catalog#index'
  get 'brands', to: 'store/manufacturers#index', as: 'brands'
  get 'shops', to: 'store/shops#index', as: 'shops'
  get 'promos', to: 'store/promos#index', as: 'promos'
  get 'promos/:id', to: 'store/promos#show', as: 'promo'


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'products_light', to: 'products_light#index', as: 'products_light'
    resources :activity_logs, only: [:index]
    resources :categories
    resources :collections
    resources :products
    resources :pictures
    resources :sale_sizes
    resources :product_types
    resources :sizes
    resources :incrustations
    resources :incrustation_items
    resources :metal_colors
    resources :metal_types
    resources :kits
    resources :manufacturers
    resources :shops
    resources :chain_types
    resources :promos
    resources :slides
    resources :main_page_blocks
    resources :users
    resource :users, only: [:update_password, :edit_password] do
      collection do
        patch ':id/update_password', to: 'users#update_password'
        get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      end
    end
  end

end

app/controllers/admin/products_light_controller.rb
class Admin::ProductsLightController < Admin::AdminController
  def index
    @products = Product.includes(:manufacturer)
                    .includes(:sale_size)
                    .includes(:shops)
                    .includes(:sizes)
                    .includes(:category)
                    .includes(:product_type)
                    .includes(:kit)
                    .includes(:collection)
                    .includes(:pictures)
                    .all.order(updated_at: :desc)
    #TODO Сделать загрузку данных для главной страницы
  end
end

app/views/admin/products_light/edit.html.erb
<div class="row" style="position: relative">
  <div id="notice" class="alert alert-success"><%= notice %></div>
  <h1 class="panel-heading">Редактирование товара</h1>
</div>

<%= link_to 'Показать', admin_product_path(@product), class: 'btn btn-default pull-left mr10' %>

<!--Кнопка назад-->
<%if @from_products%>
    <%= link_to 'Назад', admin_products_path, class: 'btn btn-default' %>
<%else%>
    <%if @from_category%>
      <%= link_to 'Назад', admin_category_path(@category), class: 'btn btn-default' %>
    <%else%>
      <%if @from_collection%>
            <%= link_to 'Назад', admin_collection_path(@collection), class: 'btn btn-default' %>
      <%else%>
            <%= link_to 'Назад', admin_products_path, class: 'btn btn-default' %>
      <%end%>
    <%end%>
<%end%>


<%= link_to admin_product_path(@product), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger pull-right' do %>
    Удалить изделие <i class="fa fa-trash" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Удалить товар"></i>
<% end %>
<%= render 'form', product: @product %>
<%= render 'nav_toggling', flag: @from_new %>

app/views/admin/products_light/index.html.erb
<!-- Page Content -->
<div class="row">
  <div id="notice" class="alert alert-success"><%= notice %></div>
  <h1 class="page-header">Изделия</h1>
</div>
<ul class="list-inline">
  <li><%= link_to  new_admin_product_path, class: 'btn btn-success' do %>
        Добавить изделие
    <i class="fa fa-plus"></i>
    <% end %>
  </li>

  <li class="dropdown">
    <a class="dropdown-toggle btn btn-default" data-toggle="dropdown" href="#" aria-expanded="true">
      Дополнительно <i class="fa fa-plus"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li><%= link_to 'Размеры', new_admin_size_path %></li>
      <li><%= link_to 'Виды изделий', new_admin_product_type_path %></li>
      <li><%= link_to 'Вставки', new_admin_incrustation_path %></li>
      <li><%= link_to 'Цвета', new_admin_metal_color_path %></li>
      <li><%= link_to 'Металлы', new_admin_metal_type_path %></li>
      <li><%= link_to 'Скидки', new_admin_sale_size_path %></li>
    </ul>
  </li>

</ul>
<i class="fa fa-refresh fa-spin fa-3x fa-fw" style="display: block; margin: auto"></i>
<div class="row">
<div class="panel panel-default" style="margin-top: 20px; margin-bottom: 60px; visibility: hidden;" id="table">
  <!-- /.panel-heading -->
  <div class="panel-body">
    <table  width="100%" class="table table-striped table-bordered table-hover"  id="productDataTable">
      <thead>
      <tr>
        <th>id</th>
        <th>Артикул</th>
        <th>Производ.</th>
        <th>Вес</th>
        <th>Цена гр.</th>
        <th>Цена</th>
        <th>%</th>
        <th>Цена %</th>
        <th>Размер</th>
        <th>Приор.</th>
        <th>Вид изделия</th>
        <th>Набор</th>
        <th>Коллекция</th>
        <th>
          <i class="fa fa-star" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Хит? Поиск: хит"></i>
        </th>
        <th>
          <i class="fa fa-home" aria-hidden="true"  data-toggle="tooltip" data-placement="top" data-original-title="На главной? Поиск: главная"></i>
        </th>
        <th>
          <i class="fa fa-picture-o" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Есть фото? Поиск: фото"></i>
        </th>
        <th><i class="fa fa-heart" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Вам понравится? Поиск: нрав"></i>
        </th>
        <th>
          <i class="fa fa-eye" aria-hidden="true"  data-toggle="tooltip" data-placement="top" data-original-title="Виден? Поиск: виден"></i>
        </th>
        <th class="dt-body-center"></th>
        <th class="dt-body-center"></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th class="filterring">id</th>
        <th class="filterring">Артикул</th>
        <th class="filterring">Производитель</th>
        <th class="filterring">Вес</th>
        <th class="filterring">Цена гр.</th>
        <th class="filterring">Цена</th>
        <th class="filterring">%</th>
        <th class="filterring">Цена %</th>
        <th class="filterring">Размер</th>
        <th class="filterring">Приор.</th>
        <th class="filterring">Вид изделия</th>
        <th class="filterring">Набор</th>
        <th class="filterring">Коллекция</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th class="dt-body-center"></th>
        <th class="dt-body-center"></th>
        <th></th>
        <th></th>
      </tr>
      </tfoot>

      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.artikul %></td>
            <td>
              <% if product.manufacturer != nil && product.manufacturer.title != '' %>
                  <%= truncate( product.manufacturer.title, length: 12, omission: '..') %>
              <%end%>
            </td>
            <td><%= product.weight %></td>
            <td><%= product.price_per_gramm %></td>
            <td><%= product.price %></td>
            <td>
              <% if product.sale_size != nil && product.sale_size.sale_percent != '' %>
                  <%= product.sale_size.sale_percent %> %
              <%end%>
            </td>
            <td><%= product.new_price %></td>
            <td style="min-width: 117px;">
              <% if product.shops.size %>
                  <% product.shops.each do |shop|%>
                      <% if product.get_shop_sizes(shop).size%>
                          <div data-toggle="tooltip" data-placement="top" data-original-title="<%=shop.title%>">
                            <%= truncate( shop.title, length: 2, omission: ':') %>
                            <% product.get_shop_sizes(shop).each do |size|%>
                                <%=size.size%>
                            <%end%>
                          </div>
                      <%end%>
                  <%end%>
              <%end%>
            </td>
            <td><%= product.priority %></td>
            <td>
              <% if product.product_type != nil && product.product_type.title != '' %>
                  <%= product.product_type.title %>
              <%end%>
            </td>
            <td>
              <% if product.kit != nil && product.kit.title != '' %>
                  <%= product.kit.title %>
              <%end%>
            </td>
            <td>
              <% if product.collection != nil && product.collection.title != '' %>
                  <%= product.collection.title %>
              <%end%>
            </td>
            <td class="text-center align-middle">
              <% if product.hit %>
                  <i class="fa fa-check text-success" aria-hidden="true"></i>
                  <span class="hidden">хит</span>
              <% else %>
                  <i class="fa fa-times text-secondary" aria-hidden="true"></i>
              <%end%>
            </td>
            <td class="text-center align-middle">
              <% if product.to_main_page %>
                  <i class="fa fa-check text-success" aria-hidden="true"></i>
                  <span class="hidden">главная</span>
              <% else %>
                  <i class="fa fa-times text-secondary" aria-hidden="true"></i>
              <%end%>
            </td>
            <td class="text-center align-middle">
              <% if product.pictures.size > 0%>
                  <i class="fa fa-check text-success" aria-hidden="true"></i>
                  <span class="hidden">Фото</span>
              <% else %>
                  <i class="fa fa-times text-secondary" aria-hidden="true"></i>
              <%end%>
            </td>
            <td class="text-center align-middle">
              <% if product.recommendation %>
                  <i class="fa fa-check text-success" aria-hidden="true"></i>
                  <span class="hidden">нрав</span>
              <% else %>
                  <i class="fa fa-times text-secondary" aria-hidden="true"></i>
              <%end%>
            </td>
            <td class="text-center align-middle">
              <% if product.visible %>
                  <i class="fa fa-check text-success" aria-hidden="true"></i>
                  <span class="hidden">Виден</span>
              <% else %>
                  <i class="fa fa-times text-secondary" aria-hidden="true"></i>
              <%end%>
            </td>

            <td align="center" style="vertical-align: middle; padding-top: 12px" >
              <!--Узкое место роутов-->
              <a target="_blank" href="/products/<%= product.id %>">
                <i class="fa fa-external-link fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Открыть в новой вкладке страницу изделия"></i>
              </a>
            </td>
            <td align="center" style="vertical-align: middle; ">
              <a href="/admin/products/<%= product.id %>">
                <i class="fa fa-bars fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Просмотреть всю информацию"></i>
              </a>
            </td>
            <td align="center" style="vertical-align: middle">
              <a href="/admin/products/<%= product.id %>/edit">
                <i class="fa fa-pencil-square fa-2x" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Редактировать"></i>
              </a>
            </td>
            <td align="center" style="vertical-align: middle">
              <a data-confirm="Вы уверены?" rel="nofollow" data-method="delete" href="/admin/products/<%= product.id %>">
                <i class="fa fa-times fa-2x" style="color: red;" aria-hidden="true" data-toggle="tooltip" data-placement="top" data-original-title="Удалить изделие"></i>
              </a>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>