config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations,:sessions]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  root 'store/main_page#index'

  get 'products/:id', to: 'store/products#show', as: 'product'
  get 'categories/:id', to: 'store/categories#show', as: 'category'
  get 'catalog', to: 'store/catalog#index'
  get 'brands', to: 'store/manufacturers#index', as: 'brands'
  get 'shops', to: 'store/shops#index', as: 'shops'
  get 'promos', to: 'store/promos#index', as: 'promos'
  get 'promos/:id', to: 'store/promos#show', as: 'promo'


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'products_light', to: 'products_light#index', as: 'products_light'
    resources :activity_logs, only: [:index]
    resources :categories
    resources :collections
    resources :products
    resources :pictures
    resources :sale_sizes
    resources :product_types
    resources :sizes
    resources :incrustations
    resources :incrustation_items
    resources :metal_colors
    resources :metal_types
    resources :kits
    resources :manufacturers
    resources :shops
    resources :chain_types
    resources :promos
    resources :slides
    resources :main_page_blocks
    resources :users
    resource :users, only: [:update_password, :edit_password] do
      collection do
        patch ':id/update_password', to: 'users#update_password'
        get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      end
    end
  end

end

app/models/kit.rb
class Kit < ApplicationRecord
  has_many :products

  validates :title, presence: true, length: {in: 1..50}

  def getKitPrice
    kit_price = 0
    self.products.each do |product|
      if product.price != nil
        kit_price += product.price
      end
    end
    #если в конце метода указываешь значене какое то, то это типа return
    kit_price
  end

  def getKitNewPrice
    kit_price = 0
    self.products.each do |product|
      if product.new_price != nil
        kit_price += product.new_price
      else
        if product.price != nil
          kit_price += product.price
        end
      end
    end
    #если в конце метода указываешь значене какое то, то это типа return
    kit_price
  end

end

app/controllers/admin/kits_controller.rb
class Admin::KitsController < Admin::AdminController
  before_action :set_kit, only: [:show, :edit, :update, :destroy]
  before_action :set_selecting_products, only: [:new, :create, :edit, :update]

  def index
    @kits =  Kit.includes(:products).order(products_count: :desc)
    if @kits.empty?
      @max_cols = 0
    else
      @max_cols = @kits.first.products_count
    end
  end

  def show
  end

  def new
    @kit = Kit.new
  end

  def edit
  end

  def create
    @kit = Kit.new(kit_params)
    if @kit.save
      Kit.reset_counters(@kit.id, :products)
      record_activity(@kit)
      redirect_to admin_kit_path(@kit), notice: 'Комплект был добавлен.'
    else
      render :new
    end
  end


  def update
    if @kit.update(kit_params)
      record_activity(@kit)
      redirect_to admin_kit_path(@kit), notice: 'Комплект был обновлен.'
    else
      render :edit
    end
  end

  def destroy
    @kit.products.each do |product|
      product.kit = nil
      product.save
    end
    @kit_tmp = @kit.dup
    @kit.destroy
    record_activity(@kit_tmp)
    redirect_to admin_kits_url, notice: 'Комплект был удален.'
  end

  private

  # используется в форме набора
  def set_selecting_products
    @products = Product.all.order(:title)
  end

  def set_kit
    @kit = Kit.find(params[:id])
  end

  def kit_params
    params.require(:kit).permit(:title, :product_ids => [])
  end

end

app/views/admin/kits/_form.html.erb
<%= form_for([:admin, kit]) do |f| %>
  <% if kit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kit.errors.count, "ошибка", "ошибки") %>: не удалось сохранить:</h2>

      <ul>
        <% kit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-lg-6">

    <div class="form-group">
      <%= f.label :title, 'Название' %>
      <%= f.text_field :title, :placeholder => 'Введите название  ', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :product_ids, 'Товары комплекта' %>
      <%= f.collection_select :product_ids, @products, :id, :artikul, {},
                              {:multiple => '',
                               include_blank: 'Пусто',
                               class: 'selectpicker',
                               :"data-live-search" => 'true',
                               :"data-width" => 'fit',
                               :"data-live-Search-Placeholder" => 'Введите артикул',
                               :"title" => 'Выберете артикулы...'}
      %>
    </div>

    <div class="actions text-right mt10" >
      <%= f.submit 'Применить', class: 'btn btn-success'%>
    </div>

  </div>
</div>
<% end %>

app/views/admin/kits/edit.html.erb
<div class="row">
  <h1 class="panel-heading">Редактирование комплекта</h1>
</div>
<div class="mb10">
  <%= link_to 'Показать', admin_kit_path(@kit), class: 'btn btn-default mr10'  %>
  <%= link_to 'Назад', admin_kits_path, class: 'btn btn-default'  %>
</div>

<%= render 'form', kit: @kit %>

app/views/admin/kits/index.html.erb
<div class="row">
  <h1 class="panel-heading">Комплекты</h1>
  <div id="notice" class="alert alert-success"><%= notice %></div>
</div>

<%= link_to new_admin_kit_path, class: 'btn btn-success'  do %>
    Добавить комплект
    <i class="fa fa-plus"></i>
<% end %>
<br><br>

<div class="panel panel-default">
  <div class="panel-body">
    <table  width="100%" class="table table-striped table-bordered table-hover" id="simpleDataTable">
        <thead>
          <tr>
            <th>Название</th>
            <% @max_cols.times do %>
                <th>Артикул</th>
            <%end%>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @kits.each do |kit| %>
            <tr>
              <td><%= kit.title %></td>
              <% @max_cols.times do |i|%>
                  <%if kit.products[i].nil?%>
                      <td></td>
                  <%else%>
                      <td><%= link_to kit.products[i].artikul, edit_admin_product_path(kit.products[i]) %></td>
                  <%end%>
              <%end%>
              <td><%= link_to 'Показать', admin_kit_path(kit) %></td>
              <td><%= link_to 'Изменить', edit_admin_kit_path(kit) %></td>
              <td><%= link_to 'Удалить', admin_kit_path(kit), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/admin/kits/new.html.erb
<div class="row">
  <h1 class="panel-heading">Новый комплект</h1>
</div>

<%= link_to 'Назад', admin_kits_path,  class: 'btn btn-default mb10' %>
<%= render 'form', kit: @kit %>

app/views/admin/kits/show.html.erb
<div class="row">
  <h1 class="panel-heading">Комлект</h1>
  <div id="notice" class="alert alert-success"><%= notice %></div>
</div>
<p>
  <strong>Название:</strong>
  <%= @kit.title %>
</p>

<% @kit.products.each do |product| %>
    <p>
      <strong>Артикул:</strong>
      <%= link_to admin_product_path(product) do %>
      <%= product.artikul %>
      (<%= product.category.title %>)
      <% end %>
    </p>
<% end %>

<%= link_to 'Изменить', edit_admin_kit_path(@kit),  class: 'btn btn-default mr10' %>
<%= link_to 'Назад', admin_kits_path,  class: 'btn btn-default' %>