config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations,:sessions]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  root 'store/main_page#index'

  get 'products/:id', to: 'store/products#show', as: 'product'
  get 'categories/:id', to: 'store/categories#show', as: 'category'
  get 'catalog', to: 'store/catalog#index'
  get 'brands', to: 'store/manufacturers#index', as: 'brands'
  get 'shops', to: 'store/shops#index', as: 'shops'
  get 'promos', to: 'store/promos#index', as: 'promos'
  get 'promos/:id', to: 'store/promos#show', as: 'promo'


  namespace :admin do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'products_light', to: 'products_light#index', as: 'products_light'
    resources :activity_logs, only: [:index]
    resources :categories
    resources :collections
    resources :products
    resources :pictures
    resources :sale_sizes
    resources :product_types
    resources :sizes
    resources :incrustations
    resources :incrustation_items
    resources :metal_colors
    resources :metal_types
    resources :kits
    resources :manufacturers
    resources :shops
    resources :chain_types
    resources :promos
    resources :slides
    resources :main_page_blocks
    resources :users
    resource :users, only: [:update_password, :edit_password] do
      collection do
        patch ':id/update_password', to: 'users#update_password'
        get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      end
    end
  end

end

app/models/promo.rb
class Promo < ApplicationRecord
  # изображение превью
  belongs_to :preview, class_name: 'Picture', optional: true
  # изображение для текста акции
  belongs_to :picture, class_name: 'Picture', optional: true
  has_many :products_promos, dependent: :delete_all
  has_many :products, :through => :products_promos
end

app/controllers/admin/promos_controller.rb
class Admin::PromosController < Admin::AdminController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  def index
    @promos = Promo.all
  end

  def show
  end

  def new
    @promo = Promo.new
  end

  def edit
  end

  def create
    @promo = Promo.new(promo_params)
    if params[:preview]
      preview = Picture.create(image: params[:preview])
      @promo.preview = preview
    end
    if params[:picture]
      picture = Picture.create(image: params[:picture])
      @promo.picture = picture
    end
    respond_to do |format|
      if @promo.save
        record_activity(@promo)
        format.html {redirect_to edit_admin_promo_path(@promo), notice: 'Акция была успешно создана.'}
        format.json {render :show, status: :created, location: @promo}
      else
        format.html {render :new}
        format.json {render json: @promo.errors, status: :unprocessable_entity}
      end
    end
  end

  def update

    if params[:preview]
      preview = Picture.create(image: params[:preview])
      @promo.preview = preview
    end
    if params[:picture]
      picture = Picture.create(image: params[:picture])
      @promo.picture = picture
    end

    respond_to do |format|
      if @promo.update(promo_params)
        record_activity(@promo)
        format.html {redirect_to edit_admin_promo_path(@promo), notice: 'Акция была успешно обновлена.'}
        format.json {render :nothing => true}
      else
        format.html {render :edit}
        format.json {render json: @promo.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    if !@promo.preview.nil?
      @promo.preview.destroy
    end
    if !@promo.picture.nil?
      @promo.picture.destroy
    end
    @promo_tmp = @promo.dup
    @promo.destroy
    record_activity(@promo_tmp)
    respond_to do |format|
      format.html {redirect_to admin_promos_url, notice: 'Акция была успешно удалена.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_promo
    @promo = Promo.find(params[:id])
  end

  def promo_params
    params.require(:promo).permit(:title, :text)
  end
end

app/controllers/store/promos_controller.rb
class Store::PromosController < Store::StoreController
  def index
    @promos = Promo.includes(:preview).all.where.not(preview: nil).order(created_at: :desc)
  end

  def show
    @promo = Promo.find(params[:id])
  end
end

app/views/admin/promos/_form.html.erb
<%= form_for([:admin,promo], :html => {multipart: true}) do |f| %>
    <% if promo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

          <ul>
            <% promo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :title, 'Название' %>
          <%= f.text_field :title, :placeholder => 'Введите название  ', class: 'form-control' %>
        </div>

        <div class="field-group">
          <%= f.label :text, 'Текст' %>
          <%= f.text_area :text,{class: 'form-control'} %>
        </div>
      </div>
    </div>

    <div class="row">
      <!--Изображение в списке брендов-->
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :preview, 'Превью акции' %>
          <%= file_field_tag "preview", class: 'form-control' %>
        </div>
        <% if promo.preview %>
            <%= link_to admin_picture_path(promo.preview), method: :delete, :remote => true, :class => 'delete-image' do %>
                Удалить
            <% end %>
            <%= image_tag promo.preview.image, class: 'img-responsive' %>
        <% end %>
      </div>
      <!--Изображение слайдере брендов-->
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :picture, 'Изображение акции' %>
          <%= file_field_tag "picture", class: 'form-control' %>
      </div>
        <% if promo.picture %>
            <%= link_to admin_picture_path(promo.picture), method: :delete, :remote => true, :class => 'delete-image' do %>
                Удалить
            <% end %>
            <%= image_tag promo.picture.image, class: 'img-responsive' %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="actions text-center">
        <%= f.submit 'Применить', class: 'btn btn-success mb10 mr10' %>
      </div>
    </div>


<% end %>

app/views/admin/promos/edit.html.erb
<div class="row">
  <div id="notice" class="alert alert-success"><%= notice %></div>
  <h1 class="panel-heading">Редактирование акции</h1>
</div>
<div class="mb15">
  <%= link_to 'Назад', admin_promos_path, class: 'btn btn-default'  %>
</div>
<%= render 'form', promo: @promo %>

app/views/admin/promos/index.html.erb
<div class="row">
  <h1 class="panel-heading">Акции</h1>
  <div id="notice" class="alert alert-success"><%= notice %></div>
</div>
<%= link_to new_admin_promo_path, class: 'btn btn-success' do %>
    Добавить акцию
    <i class="fa fa-plus"></i>
<% end %>
<br>
<br>
<div class="panel panel-default">
  <div class="panel-body">
    <table  width="100%" class="table table-striped table-bordered table-hover" id="simpleDataTable">
      <thead>
      <tr>
        <th>Название</th>
        <th>Описание</th>
        <th>Изделий в акции</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @promos.each do |promo| %>
          <tr>
            <td><%= promo.title %></td>
            <td><%= truncate(promo.text, length: 30) %></td>
            <td><%= promo.products.size %></td>
            <td><%= link_to 'Показать', admin_promo_path(promo) %></td>
            <td><%= link_to 'Изменить', edit_admin_promo_path(promo) %></td>
            <td><%= link_to 'Удалить', admin_promo_path(promo), method: :delete, data: {confirm: 'Вы уверены?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/admin/promos/new.html.erb
<div class="row">
  <h1 class="panel-heading">Новая акция</h1>
</div>

<%= link_to 'Назад', admin_promos_path, class: 'btn btn-default mb10' %>

<%= render 'form', promo: @promo %>

app/views/admin/promos/show.html.erb
<div class="row">
  <h1 class="panel-heading">Акция</h1>
  <p id="notice"><%= notice %></p>
</div>
<p>
  <strong>Название:</strong>
  <%= @promo.title %>
</p>
<p>
  <strong>Текст:</strong>
  <%= @promo.text %>
</p>
<% if @promo.preview %>
    <p>
      <strong>Превью:</strong>
      <%= image_tag @promo.preview.image(:medium), class: 'img-responsive' %>
    </p>
<% end %>
<% if @promo.picture %>
    <p>
      <strong>Изображение в тексте:</strong>
      <%= image_tag @promo.picture.image(:medium), class: 'img-responsive' %>
    </p>
<% end %>

<%= link_to 'Изменить', edit_admin_promo_path(@promo),  class: 'btn btn-default mr10' %>
<%= link_to 'Назад', admin_promos_path,  class: 'btn btn-default' %>